name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install dependencies
      run: |
        npm install
        npm install -g @capacitor/cli
    - name: Build web assets
      run: |
        # Ensure www directory exists with basic content
        mkdir -p www/js www/css
        if [ ! -f "www/index.html" ]; then
          cp *.html www/ 2>/dev/null || echo "<!DOCTYPE html><html><head><title>SMS App</title></head><body><div id='app'><h1>SMS Messenger</h1></div><script src='js/app.js'></script></body></html>" > www/index.html
        fi
        cp -r js/* www/js/ 2>/dev/null || echo "console.log('SMS App loaded');" > www/js/app.js
        cp -r css/* www/css/ 2>/dev/null || true
    - name: Remove existing Android platform
      run: |
        if [ -d "android" ]; then
          echo "Removing existing Android platform..."
          rm -rf android
        fi
    - name: Add Android platform
      run: |
        npx cap add android
    - name: Sync Capacitor
      run: |
        npx cap sync android
    - name: Fix capacitor-sms plugins namespace and dependencies
      run: |
        # Fix @byteowls/capacitor-sms namespace
        if [ -f "node_modules/@byteowls/capacitor-sms/android/build.gradle" ]; then
          echo "Fixing @byteowls/capacitor-sms namespace..."
          if ! grep -q "namespace" node_modules/@byteowls/capacitor-sms/android/build.gradle; then
            sed -i '/android {/a\    namespace "com.byteowls.capacitor.sms"' node_modules/@byteowls/capacitor-sms/android/build.gradle
          fi
        fi

        # Fix capacitor-sms namespace and dependencies
        if [ -f "node_modules/capacitor-sms/android/capacitor-sms/build.gradle" ]; then
          echo "Fixing capacitor-sms namespace and dependencies..."
          if ! grep -q "namespace" node_modules/capacitor-sms/android/capacitor-sms/build.gradle; then
            sed -i '/android {/a\    namespace "com.byteowls.capacitor.sms"' node_modules/capacitor-sms/android/capacitor-sms/build.gradle
          fi
          # Fix old Capacitor dependency
          sed -i 's/ionic-team:capacitor-android:[0-9]\+\+/com.capacitorjs:capacitor-android:5.0.0/g' node_modules/capacitor-sms/android/capacitor-sms/build.gradle
        fi

        # Also check alternative path structure
        if [ -f "node_modules/capacitor-sms/android/build.gradle" ]; then
          echo "Fixing capacitor-sms namespace and dependencies (alternative path)..."
          if ! grep -q "namespace" node_modules/capacitor-sms/android/build.gradle; then
            sed -i '/android {/a\    namespace "com.byteowls.capacitor.sms"' node_modules/capacitor-sms/android/build.gradle
          fi
          # Fix old Capacitor dependency
          sed -i 's/ionic-team:capacitor-android:[0-9]\+\+/com.capacitorjs:capacitor-android:5.0.0/g' node_modules/capacitor-sms/android/build.gradle
        fi

        # Check if there are any other build.gradle files in capacitor-sms
        find node_modules/capacitor-sms -name "build.gradle" -exec echo "Found build.gradle: {}" \;
        find node_modules/capacitor-sms -name "build.gradle" -exec sed -i 's/ionic-team:capacitor-android:[0-9]\+\+/com.capacitorjs:capacitor-android:5.0.0/g' {} \;
    - name: Verify Android structure
      run: |
        echo "Android directory structure:"
        ls -la android/
        echo "App module check:"
        ls -la android/app/ || echo "App module not found!"
        echo "Settings gradle content:"
        cat android/settings.gradle || echo "Settings gradle not found!"
    - name: Build APK
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleDebug --no-daemon --stacktrace
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk